version: '3'

services:
  db:
    container_name: mpa-postgres
    restart: always
    image: koast/aisar-postgres:0.1
    volumes:
      - ./doc/database:/database:ro
      - ./init-sql.sh:/docker-entrypoint-initdb.d/init-sql.sh:ro
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 25432:5432

  geoserver:
    container_name: mpa-geoserver
    restart: always
    image: koast/aisar-geoserver:0.1
    volumes:
      - ./geoserver-data:/geoserver-data
    ports:
      - 28080:8080

  aisar-user:
    container_name: mpa-user
    restart: always
    image: koast/aisar-user:0.0.1-SNAPSHOT
    ports:
      - 28081:8080
    volumes:
      - /nas/volume/dev:/home/koast/data
      - /nas/data/model/OPENDR/:/home/koast/OPENDR
      - /nas/data/model/SCHISM/:/home/koast/SCHISM
    environment:
      - SPRING_PROFILES_ACTIVE=develop
      - TZ=Asia/Seoul
      - LANG=ko_KR.UTF-8
      - LC_ALL=ko_KR.UTF-8

  aisar-admin:
    container_name: mpa-admin
    restart: always
    image: koast/aisar-admin:0.0.1-SNAPSHOT
    ports:
      - 29080:29080
    environment:
      - SPRING_PROFILES_ACTIVE=develop